[tools]
deno = "latest"
lefthook = "latest"

[tasks.dev]
run = "deno task dev"

[tasks.test]
run = "deno test --allow-net --allow-read"

[tasks.e2e]
run = "npx playwright test"

[tasks.lint]
run = "deno lint"

[tasks.fmt]
run = "deno fmt"
